### ISSUE TITLE
Minimal example fails to compile under Linux

### ISSUE THREAD

**Issue by ancwrd1** [kenz-gelsoft/wxRust2#41]
The following compilation errors are shown:
```
src/generated.cpp:823:18: error: ‘class wxWindow’ has no member named ‘RegisterHotKey’
src/generated.cpp:826:18: error: ‘class wxWindow’ has no member named ‘UnregisterHotKey’
```

I think this happens because those methods are only available on Windows.

**Comment by kenz-gelsoft** [comment]
Thank you for your feedback. What version of the wx do you install? 

I know some wx APIs are platform-specific,

* Mac-specific:
  * https://github.com/kenz-gelsoft/wxRust2/blob/main/doxybindgen.toml#L84
* Windows-specific
  * https://github.com/kenz-gelsoft/wxRust2/blob/main/doxybindgen.toml#L93
  * https://github.com/kenz-gelsoft/wxRust2/blob/main/doxybindgen.toml#L111

but I did some hacky blocklisting them with very-limited environments, for Linux:

* Ubuntu 20.04 (on M1 Mac QEMU)
* Chromebook Crositini env

I'm working mainly on MacOS and Windows 10.

Will consider marking with #[target] APIs next.

**Comment by kenz-gelsoft** [comment]
I couldn't use the codelite's prebuilt packages since I have only arm64 envs. I rebuilt it for arm64 and I just got testing environment for wx3.1 on Linux.

I'll work around this by just blocking not supported APIs you reported (RegisterHotKey (and UnregisterHotKey)) for now.

About per-platform code generation, I'll work on it in https://github.com/kenz-gelsoft/wxRust2/issues/42.
